# Generated by Django 2.1.15 on 2020-03-10 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('mode_de_preparo', models.TextField()),
                ('tempo_de_preparo', models.IntegerField()),
                ('rendimento', models.TextField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_receite', models.DateField(blank=True, default=datetime.datetime.now)),
                ('publicada', models.BooleanField(default=False)),
                ('foto_receita', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
