# Generated by Django 2.1.15 on 2020-03-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receitaap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa'),
            preserve_default=False,
        ),
    ]
